delta-io/kafka-delta-ingest

Cargo.toml
The 0.26 release has a couple bug fixes, most notably a fix to compile on aarch64 
https://github.com/fede1024/rust-rdkafka/compare/v0.25.0...v0.26.0
=> Update to the latest rdkafka

Cargo.lock, Cargo.toml, src/deltalake_ext.rs, src/instrumentation.rs, src/lib.rs, tests/emails_s3_tests.rs, tests/helpers/mod.rs, tests/integration_tests.rs
Fixes #25
Here's log from tests right after the new consumer is added to the group:
```
2021-06-10T16:36:16 [INFO] - WORKER-1: Delta write for version 5 has completed in 602071 microseconds
2021-06-10T16:36:16 [INFO] - WORKER-2: Starting run loop.
2021-06-10T16:36:17 [INFO] - WORKER-1: Delta write for version 6 has completed in 516716 microseconds
2021-06-10T16:36:17 [INFO] - WORKER-1: REBALANCE - Received new partition assignment list [1, 0]
2021-06-10T16:36:17 [INFO] - WORKER-2: REBALANCE - Received new partition assignment list [2, 3]
2021-06-10T16:36:17 [INFO] - WORKER-2: Resetting state with partitions: [3, 2]
2021-06-10T16:36:17 [INFO] - WORKER-2: Seeking consumer to 3:9
2021-06-10T16:36:17 [INFO] - WORKER-2: Seeking consumer to 2:10
2021-06-10T16:36:17 [INFO] - WORKER-1: Resetting …
```
=> Add its own commit loop which resolves partition offsets conflicts

Cargo.lock, Cargo.toml, README.adoc, src/lib.rs
This PR adds the ability to load SSL parameters from the environment rather than the command line to avoid log outputs when running in cloud. 
Additionally, it includes the rdkafka ssl feature in Cargo.toml to support SSL at all.
=> Load ssl params from environment

Cargo.lock, src/deltalake_ext.rs, tests/delta_partitions_tests.rs, tests/helpers/mod.rs
Fixes #52
nulls are already handled in parquet as nulls, but not in delta log actions.
UPD: however the data path for nulls was an empty string. It's changed to the correct one - `__HIVE_DEFAULT_PARTITION__`
=> Handle null partition values

Cargo.lock, Cargo.toml, src/instrumentation.rs, src/lib.rs
This PR adds lag reporting to kafka-delta-ingest via statsd metric emissions. 
Two flavors are added - Buffer lag and write lag. Buffer lag represents the last offsets stored in buffer. Write lag represents the last offsets written to the target delta lake table. We report four metrics for each:
* total lag (sum of lag across all partitions handled by the the task/process)
* max (the highest lag observed across all handled partitions)
* min (like max but min)
* number of partitions handled by the task
Buffer lag reports roughly every minute (but requires a message receive to trigger).
Write lag reports every time a write is performed.
=> Add lag reporting

src/instrumentation.rs
I made an oversight in https://github.com/delta-io/kafka-delta-ingest/pull/77. Lag metrics should be reported as gauges (not counters - which is the default).
This PR corrects that.
=> Handle lag metrics as gauges

src/coercions.rs, src/lib.rs, src/transforms.rs
Starting as DRAFT for now. Needs integration tests and some additional robustness.
This PR adds a `coercions` module for implicitly coercing values along the lines of what [Spark's `from_json`](https://spark.apache.org/docs/latest/api/sql/index.html#from_json) function provides. Hooks are provided with this PR, but we are only implementing coercions that are relevant to our own deployments at the moment.
The two that are biting us right now are:
* The implicit coercion of nested JSON properties to the delta `string` data type
* The implicit coercion of ISO 8601 timestamp strings to the delta `timestamp` data type
I implemented this separately from the `transforms` module because the intention is quite different and that module could use some cleanup. Ultimately, I could see us potentially …
=> Add coercions module for implicit data type coercions

Cargo.lock, Cargo.toml
Using delta-rs `branch = "kdi-partition-values-quick-fix"` which contains latest used commit (rev `8d12ad`) + hotfix
=> Use hotfix version of delta-rs to address nullable partition values

src/lib.rs, src/transforms.rs, src/writer.rs
This PR contains a small code cleanup of `writer::apply_null_counts` to reduce nesting and improve readability.
@thovoll and I paired on this together (**FUN!**) as part of what will hopefully become a semi-regular code cleanup pairing session. We noted that there is some potential for additional cleanup in these two functions, but just this small change as-is represents a worthwhile well-scoped and safe incremental improvement.
=> Refactor writer::apply_null_counts to reduce nesting

Cargo.lock, Cargo.toml, src/main.rs, src/writer.rs
This commit also removes one `AppSettings` that has been removed with more recent versions of the clap crate
=> Running a general `cargo update`

Cargo.lock, Cargo.toml, src/lib.rs, src/offsets.rs, src/writer.rs, tests/helpers/mod.rs
This change is long overdue and moves kafka-delta-ingest towards using specific released versions of deltalake rather than mystery SHA1s from the git repo.
Additionally, rather than move from Decoder to RawDecoder in this commit, I will be doing that in a follow up and so this allows some deprecated APIs for the moment
=> Upgrade kafka-delta-ingest to use crates.io versions of deltalake

.gitignore, Cargo.lock, Cargo.toml, README.adoc, docker-compose.yml, src/dead_letters.rs, src/lib.rs, src/main.rs, src/serialization.rs, tests/data/default_schema.avro, tests/deserialization_tests.rs, tests/helpers/mod.rs
This was prompted by a [slack thread](https://delta-users.slack.com/archives/C01Q2RXCVSQ/p1686672498735129). This adds support for avro with or without a schema. Additionally, it adds the ability to use the confluent schema registry for schemas.
=> Avro and Schema Registry Support

src/lib.rs
This does not fix any open issue, it is rather something that was itching while reading the code. 
I'm wondering if you want to hold the write lock on the rebalance signal while handling the rebalance, so I've tried to minimize the time the lock is held. 
Current logic appears to be: 
- set the signal back to `None`, but only if there wasn't an error in `processor.table.update()`, so I've tried to keep that logic intact. 
- Also, since the lock is currently held while `processor.table.update()` is called, a new signal cannot replace it until the lock is dropped. Tried to keep that part too. 
With these changes, the base case--when there is no error handling the signal--will only see the write lock acquired once, and held for so long as it takes to call `take` on an `Option<_>`.
=> Rebalance handling: reduce time holding write lock on signal

src/lib.rs, src/main.rs, src/writer.rs, tests/end_at_last_offsets_test.rs, tests/helpers/mod.rs
When the "-e" or "--ends_at_latest_offsets" is added as an argument the application terminates when the end of the topic is reached.
The end of the topic is determined by storing the highest offsets known on startup. When a partitions reaches this offset, the partition is unassigned from the consumer.
Fixes #75 
Curious to hear any feedback!
=> Add mode that terminates kdi when the end of a topic is reached

.github/workflows/build.yml, Cargo.lock, Cargo.toml, README.adoc, build.rs, doc/HACKING.adoc, src/coercions.rs, src/cursor.rs, src/dead_letters.rs, src/delta_helpers.rs, src/lib.rs, src/main.rs, src/offsets.rs, src/transforms.rs, src/writer.rs, tests/buffer_flush_tests.rs, tests/dead_letter_tests.rs, tests/delta_partitions_tests.rs, tests/deserialization_tests.rs, tests/emails_azure_blob_tests.rs, tests/emails_s3_tests.rs, tests/end_at_last_offsets_test.rs, tests/feed_s3_tests.rs, tests/helpers/mod.rs, tests/schema_update_tests.rs
I started this work just trying to make it easier to re-use an existing Minio and Kafka configuration for the integration tests, and in the process started finding more and more that should be cleaned up in`tests/`
=> Refactoring tests to be more faster, more better, more stronger

src/main.rs
sometimes the kafka message definition matches the table definition and I end up writing `--transform 'identity: identity'`
=> allow empty transform set

.github/workflows/build.yml, Cargo.lock, Cargo.toml, bin/localstack-setup_emails.sh, contrib/Dockerfile.setup, src/delta_helpers.rs, src/lib.rs, src/offsets.rs, src/writer.rs, tests/delta_partitions_tests.rs, tests/emails_azure_blob_tests.rs, tests/helpers/mod.rs, tests/offset_tests.rs
Update deltalake to latest version.
Note that some test cases are broken due to `get_stats()` changed to private in deltalake.
=> Update deltalake to latest version

Cargo.lock, Cargo.toml, README.adoc, src/lib.rs, src/main.rs, src/serialization.rs
This pull request introduces support for ingesting gzip-compressed messages in the `kafka-delta-ingest` project. This new functionality allows users to handle gzip-compressed Kafka messages, decompressing them before further processing and ingestion into Delta Lake.
1. **New Feature: Gzip Decompression**
- Added the `--decompress_gzip` flag to the command-line options.
- Modified the `MessageDeserializerFactory` and related deserialization logic to support gzip decompression.
- Updated `main.rs` to handle the new command-line argument and pass it to the deserialization process.
- Updated `lib.rs` to integrate the new gzip decompression functionality.
- I tested the new functionality with both gzip-compressed and uncompressed messages to ensure compatibility and correct behavior in both …
=> Add flag to support gzip compressed messages

Cargo.toml
The performance improvements alone in this release are a a big deal for kafka-delta-ingest
=> chore: pin the base version of delta-rs to 0.19.0 which has loads of improvements

src/coercions.rs, src/main.rs
The original code was turning nanos into micros anyways, so we can use the more safe timestamp_micros() code.
For timestamp_nanos_opt() it can return None if the dates that cannot be represented as nanoseconds between 1677-09-21T00:12:43.145224192 and 2262-04-11T23:47:16.854775807.
=> Prevent the potential for a panic in the string_to_timestamp coercions

Cargo.toml, src/delta_helpers.rs, tests/delta_partitions_tests.rs
This allows avoiding openssl without needing to juggle the newest released version of kernel (0.6.1) and delta-rs/datafusion/arrow versions
=> chore: bump to default-engine-rustls fork

README.adoc
Updated to get examples working
=> Update 'Starting Worker Processes' in README

.dockerignore, Dockerfile
1. utilize docker cache volumes during builds to slightly improve performance
1. set runtime image to same base image distro as the build image
A clean build on my local machine takes about 30 mins. This is an attempt to
improve the iteration process by reducing the scope of changes that blow the
docker build cache and using docker volumes for large sections of the image that
are written during `cargo build` reducing recompilation of dependencies during
every docker build.
The binary produced in by the rust image doesn't run inside the alpine
container. This switches the runtime of the final image to match the upstream
base image of the rust image that is used to build.
=> docker: cache volumes in build & debian for runtime
