- .gitattributes
- .gitignore
- README.adoc
- bin/extract-test-json.sh
- tests/json/web_requests-100K.json.tar.gz
This PR adds a test data set we can use locally to play onto Kafka.
> Add test data for playing onto Kafka

- Cargo.lock
- Cargo.toml
- src/deltalake_ext.rs
- src/lib.rs
Bump delta-rs version and use new api introduced in https://github.com/delta-io/delta-rs/pull/307
> Use new low-level transaction API

- src/transforms.rs
This PR adds an additional JMESPath transform function for converting an epoch timestamp expressed in seconds to an ISO 8601 string.
> Add custom JMESPath function for converting epoch to DateTime

- Cargo.lock
- Cargo.toml
- src/deltalake_ext.rs
> Remove redundant data copying in buffer_len

- .github/workflows/build.yml
- README.adoc
- docker-compose-with-statsd.yml
- docker-compose.yml
- tests/helpers/mod.rs
- tests/playground.rs
Rename setup docker service and introduce playground env for local KDI test runs with a single command
> Make local KDI development easier

- Cargo.lock
- src/lib.rs
- src/main.rs
- tests/emails_s3_tests.rs
- tests/helpers/mod.rs
- tests/integration_tests.rs
- tests/playground.rs
Integrate checkpoints runner right into KDI loop to avoid additional infrastructure (for now at least)
> Run checkpoints within KDI

- src/dead_letters.rs
- src/deltalake_ext.rs
- src/lib.rs
- src/main.rs
- src/transforms.rs
Will add ![deny(missing_docs)] in a separate PR
> Add ![deny(warnings)]

- src/dead_letters.rs
- src/deltalake_ext.rs
- src/instrumentation.rs
- src/lib.rs
- src/main.rs
- src/transforms.rs
- tests/dead_letter_tests.rs
- tests/emails_s3_tests.rs
- tests/helpers/mod.rs
- tests/integration_tests.rs
- tests/playground.rs
- tests/schema_update_tests.rs
- tests/zero_offset_issue_tests.rs
Also:
* Use pub(crate) instead of public for modules to enable fail on unused
symbols
* Rename KafkaJsonToDelta types
* Add default impl for IngestOptions instead of the huge new(...) method
> Require rustdocs

- Cargo.lock
REF: https://github.com/delta-io/delta-rs/pull/427
> Update delta-rs to pick remove action fix

- src/value_buffers.rs
The #95 fixes dupes caused by already process offset within a record batch, however such offsets could come within a several record batches. Since last_offset is cleared once buffer is consumed, we cannot check on that. To fix the bug, we have to keep last_offset in between consumes too, e.g. do not clear it at all
> Keep last_offset when value buffer is consumed

- src/coercions.rs
Add support of `array<string>`, `array<timestamp>` and `array<struct>`
> Add array type to coercions

- Cargo.toml
- src/lib.rs
I seem to need this to build a package on nixos.
> add dynamic-linking feature

- .gitignore
- README.adoc
Starting to try this out locally, just making some minor doc edits.
> Improve docs

- Dockerfile
- README.adoc
- Created a Dockerfile that uses a multi-stage build to avoid a > 4GB image size
- Added a note in the README about writing to S3 and doing DynamoDB locking
> Add Dockerfile, update README

- Cargo.lock
- Cargo.toml
- src/main.rs
> Replace clap macros and upgrade to v4

- README.adoc
- src/main.rs
Issue #144 pointed out some argument errors that went unnoticed. I updated the argument parsing and docs such that they work as expected.
> update docs and argument parsing

- src/main.rs
There were more cli parsing issues than I initially discovered.
@rtyler I made a change to the `dlq_table_location` argument. We have it listed as optional. However, it would never work that way in practice. If a user failed to provide it, the app wouldn't work.
> fix: updated parsing of all clap properties

- src/main.rs
This is a fix to handle the flags for issue #158
> updated flag retrieval so that it does not always return true

- Cargo.lock
- Cargo.toml
- tests/emails_azure_blob_tests.rs
This builds on #141 and should be merged afterwards.
> Upgrade azure dependencies

- Dockerfile
- Makefile
> fix: update Dockerfile to a more recent Rust compiler

- Cargo.toml
deltalake-core 0.19.0 had to be yanked, oops
More context in delta-io/delta-rs#$2877
> chore: fix version specifications

- Cargo.toml
There are other fixes too, but the AWS ones I'm most interested in :smile:
> chore: upgrade to the latest delta-rs which has assume role fixes

- Cargo.toml
- src/lib.rs
Only minor changes, I was hoping this would make some other things simpler to clean up, but there's not much change here :shrug:
> chore: upgrade to the latest rdkafka
